[package]
name = "hprof-slurp"
version = "0.5.1"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
description = "JVM heap dump hprof file analyzer"
edition = "2021"

[dependencies]
nom = "7.1.3"
indicatif = "0.17.6"
clap = { version = "4.4.0", features = ["cargo"] }
indoc = "2.0.3"
ahash = "0.8.3"
thiserror = "1.0.47"
crossbeam-channel = "0.5.8"