[package]
name = "hprof-slurp"
version = "0.1.1"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2018"

[dependencies]
nom = "7.1.0"
indicatif = "0.16.2"
clap = "2.33.3"
indoc = "1.0.3"
