[package]
name = "hprof-slurp"
version = "0.2.1"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2021"

[dependencies]
nom = "7.1.0"
indicatif = "0.16.2"
clap = "3.0.13"
indoc = "1.0.3"
ahash = "0.7.6"
