[package]
name = "hprof-slurp"
version = "0.2.2"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
edition = "2021"

[dependencies]
nom = "7.1.0"
indicatif = "0.17.0-rc.4"
clap = "3.1.0"
indoc = "1.0.3"
ahash = "0.7.6"
thiserror = "1.0.30"
